#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG_CONTROL                      101
#define IDD_DIALOG_GAME                         102
#define IDD_DIALOG_DESCRIPTION                  103
#define IDI_APP_ICON                            801
#define IDC_LIST_PICTURES                       40001
#define IDC_COMBO_LAYOUT                        40101
#define IDC_COMBO_SERVE_TEAM                    40102
#define IDC_COMBO_CURRENT_SET_NR                40103
#define IDC_BUTTON_CHANGE_LAYOUT                40201
#define IDC_BUTTON_HOME_SCORE_ADD               40202
#define IDC_BUTTON_HOME_SCORE_SUB               40203
#define IDC_BUTTON_GUEST_SCORE_ADD              40204
#define IDC_BUTTON_GUEST_SCORE_SUB              40205
#define IDC_BUTTON_SET_FINISH                   40206
#define IDC_BUTTON_TECH_TIMEOUT                 40207
#define IDC_BUTTON_ABORT_TIMER                  40208
#define IDC_BUTTON_PICTURE_DOWN                 40209
#define IDC_BUTTON_PICTURE_UP                   40210
#define IDC_BUTTON_PICTURE_SHOW                 40211
#define IDC_BUTTON_PICTURE_NEXT                 40212
#define IDC_BUTTON_RESET                        40213
#define IDC_BUTTON_HOME_PLAYER_CHANGE_ADD       40214
#define IDC_BUTTON_HOME_PLAYER_CHANGE_SUB       40215
#define IDC_BUTTON_GUEST_PLAYER_CHANGE_ADD      40216
#define IDC_BUTTON_GUEST_PLAYER_CHANGE_SUB      40217
#define IDC_BUTTON_HOME_TIMEOUT_ADD             40218
#define IDC_BUTTON_HOME_TIMEOUT_SUB             40219
#define IDC_BUTTON_GUEST_TIMEOUT_ADD            40220
#define IDC_BUTTON_GUEST_TIMEOUT_SUB            40221
#define IDC_CHECKBOX_AUTO_SET_WIN               40301
#define IDC_CHECKBOX_AUTO_TIMEOUT               40302
#define IDC_CHECKBOX_VALIDATE_PLAYER_CHANGES    40303
#define IDC_CHECKBOX_PLAYER_CHANGE_SOUND        40304
#define IDC_CHECKBOX_PLAYER_CHEANGE_LAYOUT      40305
#define IDC_CHECKBOX_VALIDATE_TIMEOUTS          40306
#define IDC_CHECKBOX_TIMEOUT_SOUND              40307
#define IDC_CHECKBOX_TIMEOUT_TIMER              40308
#define IDC_CHECKBOX_TIMEOUT_LAYOUT             40309
#define IDC_CHECKBOX_AUTO_PICTURE               40310
#define IDC_EDIT_SCORE_SUMMARY                  40401
#define IDC_EDIT_HOME_SCORE                     40402
#define IDC_EDIT_GUEST_SCORE                    40403
#define IDC_EDIT_HOME_SETS_WON                  40404
#define IDC_EDIT_GUEST_SETS_WON                 40405
#define IDC_EDIT_HOME_PLAYER_CHANGES            40406
#define IDC_EDIT_GUEST_PLAYER_CHANGES           40407
#define IDC_EDIT_HOME_TIMEOUTS                  40408
#define IDC_EDIT_GUEST_TIMEOUTS                 40409
#define IDC_EDIT_GAME_DESC                      40410
#define IDC_EDIT_HOME_TEAM_DESC                 40411
#define IDC_EDIT_GUEST_TEAM_DESC                40412
#define IDC_EDIT_HOME_SET_1_RESULT              40413
#define IDC_EDIT_HOME_SET_2_RESULT              40414
#define IDC_EDIT_HOME_SET_3_RESULT              40415
#define IDC_EDIT_HOME_SET_4_RESULT              40416
#define IDC_EDIT_HOME_SET_5_RESULT              40417
#define IDC_EDIT_GUEST_SET_1_RESULT             40418
#define IDC_EDIT_GUEST_SET_2_RESULT             40419
#define IDC_EDIT_GUEST_SET_3_RESULT             40420
#define IDC_EDIT_GUEST_SET_4_RESULT             40421
#define IDC_EDIT_GUEST_SET_5_RESULT             40422
